### ISSUE TITLE
感觉新版压缩逻辑不对

### ISSUE THREAD

**Issue by lovelyelfpop** [GuoZhiQiang/Luban_iOS#11]
![tim 20180528082537](https://user-images.githubusercontent.com/5656924/40592402-6a156154-6251-11e8-961d-8e0667515388.png)

怎么看都感觉这个压缩逻辑不对。
一开始用0.06质量压一遍，不是最差质量了吗
后面在这个0.06的基础上用0.12压。。。

作者是不是想要 不超过某个文件体积的情况下，尽量使图片品质损失最小？那应该每次都在最原始的图片上用0.12、0.18压

**Comment by GuoZhiQiang** [comment]
不是 最差质量  而是 借助苹果的压缩算法，先做最大程度压缩。
如果做了最大压缩后，图片 length 还很大的时候，再尝试做 qualityCompress 递增的图片压缩
这样做的目的是减少 图片有损压缩的次数，避免图片严重掉帧

@lovelyelfpop
