### ISSUE TITLE
 文件大小计算的不对

### ISSUE THREAD

**Issue by lzj509649444** [GuoZhiQiang/Luban_iOS#2]
size before compressed == 6427.179688 Kb
Luban-iOS image data size after compressed ==38.208984 kb
压缩后说是38kb多一点，但是我把压缩后的图片上传到七牛，显示352kb多点

upload success
下面是七牛返回的结果，我根据hash 的key找到的文件，见下图
Optional(<QNResponseInfo= id: 4218172F-5333-49E4-A722-AB87305A486F, ver: 7.2.3, status: 200, requestId: EDYAAASwKBGWsQ8V, xlog: body;TBLMGR:1;RS:2;CFGG:3;s.ph;s.put.tw;s.put.tr:10;s.put.tw;s.put.tr:8;s.ph;PFDS:8;PFDS:11;body;TBLMGR:1;UC:8;CFGG:10;rs4_3.sel/not found;rdb.g/no such key;DBD/404;v4.get/Document not found;rs4_3.ins:2;rwro.ins:3;RS:91;rs.put:91;rs-upload.putFile:104;UP:239, xvia: (null), host: upload-z2.qiniup.com ip: (null) duration: 0.638038 s time: 1517626857 error: (null)>)
nil
Optional([AnyHashable("hash"): FjZNHGWwjxmwmwxtGRkkJFWi7EQ3, AnyHashable("key"): FjZNHGWwjxmwmwxtGRkkJFWi7EQ3])

<img width="1036" alt="2018-02-03 11 08 25" src="https://user-images.githubusercontent.com/1787221/35762520-a1b96782-08d2-11e8-8e83-d7b1821e1826.png">

**Comment by GuoZhiQiang** [comment]
我看一下，可能是获取到图片后，外部再次调用 UIImageJPEGRepresentation 生成的 nsdata 变大了。解决好之后我再发个版本

**Comment by GuoZhiQiang** [comment]
@lzj509649444  我把返回的对象 由 `UIImage` 改为了 `NSData` 。

因为 用户要使用的其实是 `NSData` ，如果返回 `UIImage` 对象，那么用户上传时还需要再次转换为 `NSData` 对象，这样就会造成你遇到的问题

你更新下 pod
