### ISSUE TITLE
我之前说这个压缩有点问题，目前已找到

### ISSUE THREAD

**Issue by HouWan** [GuoZhiQiang/Luban_iOS#6]
我之前提出这个翻译的压缩有点异常，当时没有找出来，今天遇到了：
压缩之后，照片形变严重，这个照片大小是7.3Mb，分辨率是：2419*3264
为了方便你测试，我把这个源图放我百度网盘了：

https://pan.baidu.com/s/1VD775iJs1FztH5dAIgbxGw
密码：9aeb

![image](https://user-images.githubusercontent.com/13991710/37943972-76216c34-31ac-11e8-9770-0f718ac48d2d.png)

**Comment by HouWan** [comment]
其实我知道你错在哪里了，你自己找找看，小伙子代码不认真啊😄🤣

**Comment by GuoZhiQiang** [comment]
我试试 2333

**Comment by HouWan** [comment]
对了，小伙子，压缩之前，判断下是否是GIF图，比较好一些。

**Comment by light-bo** [comment]
@HouWan 兄弟，求提示，有些图片压缩后确实比例不对了。:smile:

**Comment by light-bo** [comment]
@GuoZhiQiang 大神，知道问题了么 😄

**Comment by HouWan** [comment]
@light-bo 我可以给你我修复之后的代码

**Comment by light-bo** [comment]
@HouWan 谢谢大兄弟 😄 👍 👍 👍 可以将代码发我邮箱么   light_bo@126.com

**Comment by HouWan** [comment]
@light-bo 已发

**Comment by lovelyelfpop** [comment]
擦，楼上好东西不分享出来。。。 @HouWan @light-bo  来伊份，479858761@qq.com。谢谢

**Comment by GuoZhiQiang** [comment]
最近没有顾得上这个，如果找到原因了，可以尝试着分享出来，commit 一下代码

**Comment by light-bo** [comment]
@HouWan  大兄弟，有空的话提个 PR 吧。(现在压缩得还是有点狠，有些图片很模糊)

**Comment by GuoZhiQiang** [comment]
@HouWan @lovelyelfpop [#issues9](https://github.com/GuoZhiQiang/Luban_iOS/issues/9)
