### ISSUE TITLE
这个while好像没有意义

### ISSUE THREAD

**Issue by wadevanne** [GuoZhiQiang/Luban_iOS#8]
![image](https://user-images.githubusercontent.com/13325485/40398921-0f2a6768-5e6d-11e8-80f2-6d37fbc84fe6.png)

**Comment by lovelyelfpop** [comment]
有意义啊，如果为while 条件里 < 0.06 了，while体里面就可能就为负数了，那么 后面用的时候就会异常

**Comment by GuoZhiQiang** [comment]
@wadevanne  你可以尝试着 把 qualityCompress 改为 float 类型，有你想不到的效果。我暂时委曲求全写了 int 类型，是因为一个bug，但 int 类型是不对的，我还需要修改为只保留一位小数的值类型

**Comment by wadevanne** [comment]
这里面的逻辑等同 if (statement) 只执行一次while后qualityCompress就变成0了, 这可能是里面有一个issue说照片模糊, 因为是0值, most compressed
qualityCompress -= 0.06; equals to qualityCompress = (int)(1 - 0.06) = (int)0.94 = 0

**Comment by wadevanne** [comment]
equals to
`

    NSData *imageData = UIImageJPEGRepresentation(thumbImage, 1.f);
    
    if ((double)imageData.length / 1024.f > size) {
        
        imageData    = UIImageJPEGRepresentation(thumbImage, 0.f);
        thumbImage = [UIImage imageWithData:imageData];
    }
`

**Comment by lovelyelfpop** [comment]
原来你是说类型不对导致的 int 强制转换为0，while 没问题，是类型的问题

**Comment by GuoZhiQiang** [comment]
@wadevanne  你说的对，这个值我需要再改一下，暂时这么做的影响会小点儿

**Comment by GuoZhiQiang** [comment]
@wadevanne @lovelyelfpop  可以更新一下库
